
hello: hello.o factorial.o greeting.o
	gcc hello.o factorial.o greeting.o -o hello

hello.o: hello.c
	gcc -c hello.c

greeting.o: greeting.c
	gcc -c greeting.c

factorial.o: factorial.c
	gcc -c factorial.c
